version: '3.8'

services:
  recommendation-service:
    build: .
    container_name: recommendation-service
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://martinvaldez735:lisandro1@cluster0.ixbjj4o.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
